# Generated by Django 5.2 on 2025-05-08 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_guest_booking',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='number_of_passengers',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='is_primary_passenger',
        ),
        migrations.AlterField(
            model_name='passenger',
            name='email_address',
            field=models.EmailField(max_length=254),
        ),
        migrations.CreateModel(
            name='BookingPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary_passenger', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.passenger')),
            ],
            options={
                'unique_together': {('booking', 'passenger')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='passengers',
            field=models.ManyToManyField(through='bookings.BookingPassenger', to='bookings.passenger'),
        ),
    ]
